// <auto-generated />
namespace Aaron.MVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IndexPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndexPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "201306170352300_IndexPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
