// <auto-generated />
namespace Aaron.MVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MessagesPerDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessagesPerDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201306211331431_MessagesPerDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
